CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    apiKey VARCHAR(255) NOT NULL UNIQUE,
    roles VARCHAR(255) DEFAULT 'USER',
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY unique_username (username)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
